### ISSUE TITLE
Typo in profile questions

### ISSUE THREAD

**Issue by nguyenjenny** [nguyenjenny/spark_shared_repo#2]
Hey all,

There is a typo in the profile. It says "What's **you** favourite colour?" instead of **your**. 

Fix the typo and make a commit.

The commit message should include `#2`.
So for example:

`Correct typo in Jenny profile #2`

**Comment by nguyenjenny** [comment]
Felix fixed the typo: 66114e8
 @Boywonderpy234

**Comment by maryammahjoob** [comment]
ce206ecc528e4135dd18a165748b6a3b7f307d00

**Comment by WolvesRunStrongAndResilent** [comment]
https://github.com/nguyenjenny/spark_shared_repo/commit/f73d052333d2e563ae92a336579d2cf9bd83a6e8

**Comment by liufeli2** [comment]
4356a23
